### PR TITLE
Rebrand

### PR DESCRIPTION
**Pull request by TanujaG**
Update notification component to match new rebrand designs

http://pearson-higher-ed.github.io/design/c/notifications/#notification-drawer

@nlkluth @Sauravvaidya

### CODE REVIEW

**Comment by Sauravvaidya** [comment]
image

Not sure if you touched this as part of your changes, but on one of the notification, as you can see the very bottom of the notification does not have a gap between it and the bottom of the page, making it look a little funky.

**Comment by Sauravvaidya** [comment]
image

If you can notice, I see that the text "app gives y..." is slightly cut off from the bottom.

**Comment by marcdonovan** [comment]
Hey Pearson folks. I miss you guys...

**Comment by marcdonovan** [comment]
I am working at Travelport just up the road. I should come visit.

**Comment by TanujaG** [comment]
@marcdonovan  how are you doing marc ?Yeah, you should come visit sometime :) ....

**Pull request merged**
