### PR TITLE
add style class pe-label pe-label--large to headings and header icons

### PR DESCRIPTION
**Pull request by JasonLantz**
http://jira.pearsoncmg.com/jira/browse/DES-345

### CODE REVIEW

**Comment by loahou04** [comment]
we may need to change these h1s to h2s.  Does it still need these labels?

**Comment by JasonLantz** [comment]
Parker and Joe are saying that the Headings should be the pe-label--large.... i think it's regardless of which header tag you use.  I put a link to the jira story above so you can see their comments...

**Comment by JasonLantz** [comment]
can this get a comment or approval?

**Comment by wyseguyonline** [comment]
Looks like this branch still has tests not passing and there are conflicts.

**Comment by JasonLantz** [comment]
changes are coming into master creating the conflicts...  fixed the merge conflict.

**Comment by loahou04** [comment]
Travis-ci does not work with this branch.  Please make sure to run npm run build to verify everything passes otherwise its approved

**Comment by JasonLantz** [comment]
i get a warning..... is this expected?
screen shot 2016-07-06 at 9 46 53 am

**Pull request merged**
